// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs0BGd68dI2SFEggfK1vxOlVqT6-oNv0s',
    appId: '1:1098996964936:web:f335d3e0acb93a3841c27d',
    messagingSenderId: '1098996964936',
    projectId: 'newproject-4cd8f',
    authDomain: 'newproject-4cd8f.firebaseapp.com',
    storageBucket: 'newproject-4cd8f.appspot.com',
    measurementId: 'G-JSGHT33J0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYA5I-6oPxxv0Snwij3aoSi0ZsuZcGx0',
    appId: '1:1098996964936:android:60f1cf13c39731c241c27d',
    messagingSenderId: '1098996964936',
    projectId: 'newproject-4cd8f',
    storageBucket: 'newproject-4cd8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAkSe-R1Y3uc41GBJJq124ki_CHH8sbVI',
    appId: '1:1098996964936:ios:3f510a17ca6dcf4241c27d',
    messagingSenderId: '1098996964936',
    projectId: 'newproject-4cd8f',
    storageBucket: 'newproject-4cd8f.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAkSe-R1Y3uc41GBJJq124ki_CHH8sbVI',
    appId: '1:1098996964936:ios:930ea7650849aa0041c27d',
    messagingSenderId: '1098996964936',
    projectId: 'newproject-4cd8f',
    storageBucket: 'newproject-4cd8f.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
